import Document, { Html, Head, Main, NextScript } from 'next/document';

export default class MyDocument extends Document {
  render() {
    return (
      <Html>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/football_icon.png" />
          <link
            href="https://db.onlinewebfonts.com/c/88978184a438c2447fe0faa001f15a34?family=Futura+Maxi+CG+Bold"
            rel="stylesheet"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
